#!/bin/bash
SINGULARITY_BINDPATH="/gs2,/gs3,/gs4,/gs5,/gs6,/gs7,/gs8,/gpfs,/spin1,/data,/scratch,/fdb,/lscratch"
export SINGULARITY_BINDPATH
dir=$(dirname "$0")
args="$@"
singularity exec --nv /usr/local/apps/basset/0.1.0/basset.img $args
