#!/bin/bash
SINGULARITY_BINDPATH="/vf,/gs3,/gs4,/gs5,/gs6,/gs7,/gs8,/gs9,/gs10,/gs11,/gpfs,/spin1,/data,/scratch,/fdb,/lscratch"
export SINGULARITY_BINDPATH
dir=$(dirname  "$0")
cmd=$(basename "$0")
args="$@"
echo "Running \"singularity exec $dir/rDock-2013.1.img  /rDock_2013.1_src/bin/$cmd $args\" "
singularity exec $dir/rDock-2013.1.img /rDock_2013.1_src/bin/$cmd  $args
